//
//  ALPlace.h
//  Alohar
//
//  Created by Jianming Zhou on 3/16/12.
//  Copyright (c) 2012 Alohar Mobile Inc.. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>

typedef enum {
    kCategoryGeneric,
    kCategoryHome,
    kCategoryWork,
    kCategorySchool,
    kCategoryHotel,
    kCategoryFitness,
    kCategoryBeauty,
    kCategoryNaturalSetting,
    kCategoryEntertainment,
    kCategoryStore,
    kCategoryBar,
    kCategoryCoffeeTea,
    kCategoryRestaurant,
} placeCategoryType ;

/*!
 * An ALPlace is an object that manages a POI. It has basic
 * meta-data about the place such as name, address, location etc. Additionally, 
 * it has extra information generated by Alohar such as visitCount 
 *
 *
 */
@interface ALPlace : NSObject

/*!
 The unique identifier for this place on Alohar's platform.
 */
@property (nonatomic) NSInteger placeID;
/*!
 The number of times the *current* user has visited this place.
 */
@property (nonatomic) NSInteger visitCount;
/*!
 The name of the place, for example "Mo's Irish Pub".
 */
@property (nonatomic, strong) NSString *name;
/*!
 The Lat/Lng of the place. See Apple's documentation for CLLocation information.
 */
@property (nonatomic, strong) CLLocation *location;
/*!
 The full address of this place, for example "2500 N Mayfair Rd, Wauwatosa, WI 53226, United States". At this time, individual address components (street, city, country, zip, etc) are unavailable.
 */
@property (nonatomic, strong) NSString *address;
/*!
 The phone number of this place, for example "(414) 290-9780".
 */
@property (nonatomic, strong) NSString *phone;
/*!
 URL for a small (~ 75x75px) icon representing the category of this place, for example http://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png
 */
@property (nonatomic, strong) NSString *iconURL;
/*!
 URL for more information about a place (usually Google Places). For example, http://maps.google.com/maps/place?cid=881972093658747415
 */
@property (nonatomic, strong) NSString *webURL;
/*!
 A string identifier for this category of place, for example "electronics_store"
 */
@property (nonatomic, strong) NSString *category;
/*!
 A string identifier for the subcategory of this place, for example "store"
 */
@property (nonatomic, strong) NSString *subCategory;


@end
